# Generated by Django 5.1.7 on 2025-05-20 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.JSONField(help_text='Store all questions in JSON format')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='api.project')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='api.dynamictable')),
            ],
        ),
    ]
