# Generated by Django 3.1.12 on 2025-02-27 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wake_Up_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('measurement_quality', models.CharField(blank=True, choices=[('good', 'Good'), ('okay', 'Okay'), ('poor', 'Poor')], max_length=5, null=True)),
                ('RMSSD', models.FloatField(blank=True, null=True)),
                ('SDNN', models.FloatField(blank=True, null=True)),
                ('HR', models.FloatField(blank=True, null=True)),
                ('emotional_wellness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hours_of_sleep', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quality_of_sleep', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('muscle_pain', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tiredness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('menstruation', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=20, null=True)),
                ('injury', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=20, null=True)),
                ('comments', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wake_up', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('m', 'M'), ('f', 'F')], default='m', max_length=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Training_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type_of_activity', models.CharField(blank=True, choices=[('taekwondo', 'Taekwondo'), ('físico', 'Físico'), ('competición', 'Competición'), ('recovery', 'Recovery'), ('mental coaching', 'Mental Coaching')], max_length=15, null=True)),
                ('time_of_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('perceived_strain_of_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pain', models.TextField()),
                ('comments', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post_training', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='wake_up_data',
            constraint=models.UniqueConstraint(fields=('date', 'user'), name='unique_wake_up'),
        ),
    ]
