# Generated by Django 3.1.12 on 2025-02-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_training_data',
            name='physical_training_type',
            field=models.CharField(blank=True, choices=[('específico', 'Específico'), ('fuerza', 'Fuerza'), ('test', 'Test')], max_length=10, null=True),
        ),
    ]
