# Generated by Django 3.1.12 on 2025-02-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_dashboard', '0002_post_training_data_physical_training_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_training_data',
            name='type_of_activity',
        ),
    ]
