# Generated by Django 3.1.12 on 2025-02-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_dashboard', '0003_remove_post_training_data_type_of_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_training_data',
            name='type_of_activity',
            field=models.CharField(blank=True, choices=[('taekwondo', 'Taekwondo'), ('físico', 'Físico'), ('competición', 'Competición'), ('recovery', 'Recovery'), ('mental coaching', 'Mental Coaching')], max_length=15, null=True),
        ),
    ]
