# Generated by Django 3.1.12 on 2025-02-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_dashboard', '0004_post_training_data_type_of_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_training_data',
            name='physical_training_type',
        ),
    ]
