# Generated by Django 3.1.12 on 2025-02-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_dashboard', '0005_remove_post_training_data_physical_training_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_training_data',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post_training_data',
            name='pain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post_training_data',
            name='type_of_activity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
