# Generated by Django 3.1.12 on 2025-03-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_dashboard', '0006_auto_20250227_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='wake_up_data',
            name='chispa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
