# Generated by Django 5.1.7 on 2025-09-25 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_dashboard', '0008_alter_post_training_data_id_alter_profile_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wake_up_data',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='Main_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('data_collection', models.CharField(blank=True, choices=[('wellnes', 'Wake Up Data'), ('training', 'Post Training Data')], max_length=10, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_main_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'user', 'data_collection'), name='cpk')],
            },
        ),
    ]
