# Generated by Django 5.1.7 on 2025-04-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_dashboard', '0008_trainings_alter_post_training_data_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_training_data',
            name='type_of_activity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
