# Generated by Django 5.1.7 on 2025-03-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_dashboard', '0008_alter_post_training_data_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_training_data',
            name='perceived_strain_of_activity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
