# Generated by Django 5.1.7 on 2025-04-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_dashboard', '0009_alter_post_training_data_type_of_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainings',
            old_name='weigth',
            new_name='weight',
        ),
    ]
