# Generated by Django 5.1.7 on 2025-09-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_dashboard', '0009_alter_wake_up_data_comments_main_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_data',
            name='data_collection',
            field=models.CharField(blank=True, choices=[('wellness', 'Wake Up Data'), ('training', 'Post Training Data')], max_length=10, null=True),
        ),
    ]
