# Generated by Django 5.1.7 on 2025-03-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_dashboard', '0009_alter_post_training_data_perceived_strain_of_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wake_up_data',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
