# Generated by Django 5.1.7 on 2025-03-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_dashboard', '0010_alter_wake_up_data_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_training_data',
            name='time_of_activity',
            field=models.FloatField(default=60),
        ),
        migrations.AlterField(
            model_name='post_training_data',
            name='type_of_activity',
            field=models.TextField(default=''),
        ),
    ]
