# Generated by Django 5.1.7 on 2025-09-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_dashboard', '0010_alter_main_data_data_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_data',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
